/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceOverviewRouteImport } from './routes/workspace-overview'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkspaceRouteImport } from './routes/dashboard.workspace'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardSummaryRouteImport } from './routes/dashboard.summary'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportRouteImport } from './routes/dashboard.report'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPptRouteImport } from './routes/dashboard.ppt'
import { Route as DashboardPapersRouteImport } from './routes/dashboard.papers'
import { Route as DashboardLiteratureRouteImport } from './routes/dashboard.literature'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardGapsRouteImport } from './routes/dashboard.gaps'
import { Route as DashboardExperimentsRouteImport } from './routes/dashboard.experiments'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard.downloads'
import { Route as DashboardDatasetsRouteImport } from './routes/dashboard.datasets'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'

const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/workspace-overview',
  path: '/workspace-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSummaryRoute = DashboardSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportRoute = DashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPptRoute = DashboardPptRouteImport.update({
  id: '/ppt',
  path: '/ppt',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPapersRoute = DashboardPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiteratureRoute = DashboardLiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGapsRoute = DashboardGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperimentsRoute = DashboardExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatasetsRoute = DashboardDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace-overview': typeof WorkspaceOverviewRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/experiments': typeof DashboardExperimentsRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/literature': typeof DashboardLiteratureRoute
  '/dashboard/papers': typeof DashboardPapersRoute
  '/dashboard/ppt': typeof DashboardPptRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace-overview': typeof WorkspaceOverviewRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/experiments': typeof DashboardExperimentsRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/literature': typeof DashboardLiteratureRoute
  '/dashboard/papers': typeof DashboardPapersRoute
  '/dashboard/ppt': typeof DashboardPptRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace-overview': typeof WorkspaceOverviewRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/datasets': typeof DashboardDatasetsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/experiments': typeof DashboardExperimentsRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/literature': typeof DashboardLiteratureRoute
  '/dashboard/papers': typeof DashboardPapersRoute
  '/dashboard/ppt': typeof DashboardPptRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/workspace-overview'
    | '/dashboard/chat'
    | '/dashboard/datasets'
    | '/dashboard/downloads'
    | '/dashboard/experiments'
    | '/dashboard/gaps'
    | '/dashboard/help'
    | '/dashboard/history'
    | '/dashboard/literature'
    | '/dashboard/papers'
    | '/dashboard/ppt'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/summary'
    | '/dashboard/upload'
    | '/dashboard/workspace'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/workspace-overview'
    | '/dashboard/chat'
    | '/dashboard/datasets'
    | '/dashboard/downloads'
    | '/dashboard/experiments'
    | '/dashboard/gaps'
    | '/dashboard/help'
    | '/dashboard/history'
    | '/dashboard/literature'
    | '/dashboard/papers'
    | '/dashboard/ppt'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/summary'
    | '/dashboard/upload'
    | '/dashboard/workspace'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/workspace-overview'
    | '/dashboard/chat'
    | '/dashboard/datasets'
    | '/dashboard/downloads'
    | '/dashboard/experiments'
    | '/dashboard/gaps'
    | '/dashboard/help'
    | '/dashboard/history'
    | '/dashboard/literature'
    | '/dashboard/papers'
    | '/dashboard/ppt'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/report'
    | '/dashboard/settings'
    | '/dashboard/summary'
    | '/dashboard/upload'
    | '/dashboard/workspace'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-overview': {
      id: '/workspace-overview'
      path: '/workspace-overview'
      fullPath: '/workspace-overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace': {
      id: '/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/summary': {
      id: '/dashboard/summary'
      path: '/summary'
      fullPath: '/dashboard/summary'
      preLoaderRoute: typeof DashboardSummaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/report': {
      id: '/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ppt': {
      id: '/dashboard/ppt'
      path: '/ppt'
      fullPath: '/dashboard/ppt'
      preLoaderRoute: typeof DashboardPptRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/papers': {
      id: '/dashboard/papers'
      path: '/papers'
      fullPath: '/dashboard/papers'
      preLoaderRoute: typeof DashboardPapersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/literature': {
      id: '/dashboard/literature'
      path: '/literature'
      fullPath: '/dashboard/literature'
      preLoaderRoute: typeof DashboardLiteratureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gaps': {
      id: '/dashboard/gaps'
      path: '/gaps'
      fullPath: '/dashboard/gaps'
      preLoaderRoute: typeof DashboardGapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experiments': {
      id: '/dashboard/experiments'
      path: '/experiments'
      fullPath: '/dashboard/experiments'
      preLoaderRoute: typeof DashboardExperimentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/datasets': {
      id: '/dashboard/datasets'
      path: '/datasets'
      fullPath: '/dashboard/datasets'
      preLoaderRoute: typeof DashboardDatasetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardDatasetsRoute: typeof DashboardDatasetsRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardExperimentsRoute: typeof DashboardExperimentsRoute
  DashboardGapsRoute: typeof DashboardGapsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLiteratureRoute: typeof DashboardLiteratureRoute
  DashboardPapersRoute: typeof DashboardPapersRoute
  DashboardPptRoute: typeof DashboardPptRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardReportRoute: typeof DashboardReportRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSummaryRoute: typeof DashboardSummaryRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardDatasetsRoute: DashboardDatasetsRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardExperimentsRoute: DashboardExperimentsRoute,
  DashboardGapsRoute: DashboardGapsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLiteratureRoute: DashboardLiteratureRoute,
  DashboardPapersRoute: DashboardPapersRoute,
  DashboardPptRoute: DashboardPptRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardReportRoute: DashboardReportRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSummaryRoute: DashboardSummaryRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
